# ===========================================
# Event Definitions - ECSA Refactored
# ===========================================
"""
Typed events for the new Component architecture.
Uses Pydantic BaseModel for type safety and validation.
"""

try:
    # When executed as module
    from .main import BaseEvent, ErrorEvent
except ImportError:
    # When executed standalone/script (fallback)
    from main import BaseEvent, ErrorEvent
from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any
from langchain_core.messages import HumanMessage
import uuid
import time

# ===========================================
# Core Events
# ===========================================

class InputEvent(BaseEvent):
    """User input event"""
    type: str = "input"
    content: str = Field(..., description="User input content")
    session_id: str = Field(default="default_session", description="Session ID")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Extra metadata")

class ContextEvent(BaseEvent):
    """Event with formatted context for LLM"""
    type: str = "context"
    formatted_prompt: Optional[str] = Field(default=None, description="Formatted prompt")
    original_input: Optional[HumanMessage] = Field(default=None, description="Original input")
    session_id: str = Field(default="default_session", description="Session ID")

class LLMResponseEvent(BaseEvent):
    """Event with LLM response"""
    type: str = "llm_response"
    response: str = Field(..., description="Response generated by LLM")
    session_id: str = Field(default="default_session", description="Session ID")
    tokens_used: Optional[int] = Field(default=None, description="Tokens used")

class OutputEvent(BaseEvent):
    """Final output event for user"""
    type: str = "output"
    content: str = Field(..., description="Output content")
    session_id: str = Field(default="default_session", description="Session ID")

class UpdateSystemPromptEvent(BaseEvent):
    """Event to update system prompt"""
    type: str = "update_system_prompt"
    new_prompt: str = Field(..., description="New system prompt")
    session_id: Optional[str] = Field(default=None, description="Specific session (None = global)")

# ===========================================
# Request/Response Types for AsyncComponents
# ===========================================

def generate_uuid():
    return str(uuid.uuid4())

class GetContextRequest(BaseModel):
    """Request to get context from a session"""
    request_id: str = Field(default_factory=generate_uuid)
    session_id: str = Field(..., description="Session ID")
    max_messages: int = Field(default=10, description="Maximum number of messages")
    timeout_ms: int = Field(default=5000, description="Timeout in ms")

class GetContextResponse(BaseModel):
    """Response with context messages"""
    request_id: str
    success: bool
    messages: List[Dict[str, Any]] = Field(default_factory=list, description="History messages")
    error: Optional[str] = None

class StoreMessageRequest(BaseModel):
    """Request to store message"""
    request_id: str = Field(default_factory=generate_uuid)
    session_id: str = Field(..., description="Session ID")
    message_type: str = Field(..., description="Message type (human/ai)")  # "human" or "ai"
    content: str = Field(..., description="Message content")
    timeout_ms: int = Field(default=5000, description="Timeout in ms")

class StoreMessageResponse(BaseModel):
    """Storage confirmation response"""
    request_id: str
    success: bool
    message_id: Optional[str] = None
    error: Optional[str] = None

class LLMRequest(BaseModel):
    """Request for LLM generation"""
    request_id: str = Field(default_factory=generate_uuid)
    prompt: str = Field(...)
    llm_config: Dict[str, Any] = Field(default_factory=dict)
    timeout_ms: int = Field(default=30000)

class LLMResponse(BaseModel):
    """Response from LLM generation"""
    request_id: str
    success: bool
    response: Optional[str] = None
    tokens_used: Optional[int] = None
    error: Optional[str] = None

# ===========================================
# System Events
# ===========================================

class ComponentStatusEvent(BaseEvent):
    """Component status event"""
    type: str = "component_status"
    component_name: str = Field(..., description="Component name")
    status: str = Field(..., description="Current status")  # "initialized", "error", "shutdown"
    message: Optional[str] = Field(default=None, description="Additional message")

class AgentStatusEvent(BaseEvent):
    """Agent status event"""
    type: str = "agent_status"
    agent_id: str = Field(..., description="Agent ID")
    status: str = Field(..., description="Status")  # "starting", "running", "stopping", "stopped"
    components_count: int = Field(default=0, description="Number of components")

class MetricsEvent(BaseEvent):
    """Component metrics event"""
    type: str = "metrics"
    component_name: str = Field(..., description="Component name")
    metrics: Dict[str, Any] = Field(..., description="Metrics data")
    timestamp: float = Field(default_factory=time.time)

# ===========================================
# Error Event (already defined in main.py)
# ===========================================
# ErrorEvent is imported from main.py

__all__ = [
    # Core Events
    'InputEvent',
    'ContextEvent',
    'LLMResponseEvent',
    'OutputEvent',
    'UpdateSystemPromptEvent',

    # Request/Response
    'GetContextRequest',
    'GetContextResponse',
    'StoreMessageRequest',
    'StoreMessageResponse',
    'LLMRequest',
    'LLMResponse',

    # System Events
    'ComponentStatusEvent',
    'AgentStatusEvent',
    'MetricsEvent',

    # Error
    'ErrorEvent',
]
